### ISSUE TITLE
Clarification: time display

### ISSUE THREAD

**Issue by gamesbook** [victorbenichoux/ticktock#6]
Is it possible that the display could default to show `seconds.milliseconds` timing? ATM it seems to just round off to seconds?

**Comment by victorbenichoux** [comment]
I think this makes sense, currently we only display one unit, but I will make it so that we display two units by default, that is showing "1s230ms" vs "1s".

**Comment by gamesbook** [comment]
Thanks - that will be very helpful.

**Comment by victorbenichoux** [comment]
So, I have made the default to 2 terms (it is now released) + now you can set this as you want with the `set_format` function (https://victorbenichoux.github.io/ticktock/customize/#units). Feel free to try it out, it's just been released!

I think that it could make sense to also allow the format string to use standard Python formatting to render times instead of my own unit display. This means the format string could accept keys with the floating point values in it... If you are interested I'll try and add it some time next week 😄
